services:
  prometheus:
    image: prom/prometheus:latest    
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:9090'
    ports:
      - "9090:9090"
    
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    user: root
    volumes:
      - ./data:/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123

    ports:
      - '3000:3000'

volumes:
  prometheus_data:
